define bilguun = Character("Билгүүн", color="#8bc9ff")
define khulan = Character("Хулан", color="#ffb5ce")
define chingun = Character("Чингүн", color="#ffe1a1")
define anu = Character("Ану", color="#c8b5ff")
define bolor = Character("Болор", color="#9ae0db")
define teacher = Character("Багш")
define khulan_mother = Character("Хулангийн ээж")
define khulan_father = Character("Хулангийн аав")
define bilguun_father = Character("Аав")
define badral = Character("Бадрал", color="#adc6ef")
define older_students = Character("Залуус")